defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude: ["code-of-conduct-src"]

repos:
- name: Bridge Foundry
  description: Main repository
  url: https://github.com/bridgefoundry/bridgefoundry.github.io

encoding: utf-8
markdown: kramdown
future: true